version: '3.5'

services:
  frexdoc:
    image: tobybrave/frexdoc
    container_name: frexdoc
    ports: 
      - 5000:5000
    build: ../frontend-example-docker
    environment:
      - API_URL=https://2886795315-8000-elsy06.environments.katacoda.com # katacoda port
  beexdoc:
    image: tobybrave/beexdoc
    container_name: beexdoc
    ports:
      - 8000:8000
    build: .
    environment:
      - FRONT_URL=https://2886795315-5000-elsy06.environments.katacoda.com # katacoda port
