
version: '3.5'

services:

  frontend:
    image: tobybrave/frexdoc
    container_name: frexdoc
    ports:
      - 5000:5000
    build: ../frontend-example-docker
    environment:
      - API_URL=https://2886795276-8000-simba10.environments.katacoda.com # katacoda varying port
      
  backend:
    image: tobybrave/beexdoc
    container_name: beexdoc
    ports:
      - 8000:8000
    build: .
    environment:
      - FRONT_URL=https://2886795279-5000-ollie07.environments.katacoda.com # katacoda varying port
      - REDIS=cache
      - REDIS_PORT=6379
  
  cache:
    image: redis
    container_name: redis_cache
